### ISSUE TITLE
Demo credentials for admin doesn't work

### ISSUE THREAD

**Issue by Vishnja** [ant-vel/antVel#49]
Credentials for admin doesn't work in demo site.

**Comment by gocanto** [comment]
Yes, I am aware of it. I had to change the admin's one because somebody mess with the demo. So far, Admin is the one who controls the site configuration and I have not had time to change this in the code. 

If you want to test it out, you will have to clone the repo and install it on your machine. 

Let me know if you have any issue, I love helping.

Thanks for testing.

**Comment by Vishnja** [comment]
I will install locally. Thank you for your work!

**Comment by gocanto** [comment]
np

**Comment by Vishnja** [comment]
I have problems upgrading Homestead to latest version (with MySQL 5.7 to support for 'json' field). PostgerstSQL also gives a lot of errors. OpenServer (WAMP) with Mysql 5.7 doesn't work either: 

> exception 'ErrorException' with message 'PDO::prepare(): Unknown type 245 sent by the server. Please send a report to the developers

Really interested to see admin. (May be if someone messed with DB it would good idea to automatically reseed it once every 3-4 hours).

**Comment by gocanto** [comment]
check this link https://laravel.com/docs/5.2/homestead out and as I said, I would like to do more in this project but time my enemy these days.
